
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:3095221) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_4',
  containerIp: '10.0.3.109',
  mitmPort: 1003,
  autoAccessFixed: 1
}
2022-10-23 01:35:27.220 - [Info] MITM Version: 2
2022-10-23 01:35:27.221 - [Info] Auto Access Enabled: true
2022-10-23 01:35:27.221 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-23 01:35:27.229 - [Info] SSH man-in-the-middle server for 10.0.3.109 listening on 10.0.3.1:1003
2022-10-23 01:49:17.769 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.770 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.775 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.776 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.776 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.777 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.778 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.779 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.780 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.781 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.782 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.784 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.785 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.785 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.785 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.786 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.786 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.786 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.786 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:17.786 - [Debug] [Connection] Attacker connected: 35.190.156.43 | Client Identification: SSH-2.0-Go
2022-10-23 01:49:35.350 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.350 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.368 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.368 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.376 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.376 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.387 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.387 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.388 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.389 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.392 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.392 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.392 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.392 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.394 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.394 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.415 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.415 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.422 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.422 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.427 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.427 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.430 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.430 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.433 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.433 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.433 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.433 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.442 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.442 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.462 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.463 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.463 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.463 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.473 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.473 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.541 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.541 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:35.615 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'none'
2022-10-23 01:49:35.615 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 01:49:42.912 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:42.913 - [Debug] [Auto Access] Attacker: 35.190.156.43, Threshold: 1, Attempts: 1
2022-10-23 01:49:42.913 - [Debug] [Auto Access] Compromising the honeypot
2022-10-23 01:49:42.913 - [Debug] [Auto Access] Adding the following credentials: 'root:linux'
2022-10-23 01:49:42.969 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-23 01:49:42.972 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-23 01:49:42.972 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.109
2022-10-23 01:49:42.977 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:42.988 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:42.988 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:42.989 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:42.989 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:42.990 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:42.990 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:42.991 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-23 01:49:42.991 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:42.991 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:42.992 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:42.993 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:42.993 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:42.994 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:42.994 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:42.994 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:42.995 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:42.996 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:42.996 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:42.997 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:42.997 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:42.998 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:42.999 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:43.000 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.000 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.001 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:43.002 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.003 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.004 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:43.004 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.005 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.005 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:43.005 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.006 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.006 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-23 01:49:43.006 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.011 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.013 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:43.014 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.014 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.014 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-23 01:49:43.015 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.015 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.015 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:43.015 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.015 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.016 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:43.016 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.016 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.016 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:43.017 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.018 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.018 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-23 01:49:43.018 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.031 - [Debug] [Auth] Attacker 35.190.156.43 trying to authenticate with 'password'
2022-10-23 01:49:43.031 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-23 01:49:43.031 - [Debug] [Auth] Attacker: 35.190.156.43 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 01:49:43.052 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2022-10-23 01:49:55.672 - [Debug] [Connection] Attacker closed the connection
2022-10-23 01:49:55.674 - [Debug] [Connection] Attacker closed the connection
