
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:2369677) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_2',
  containerIp: '10.0.3.244',
  mitmPort: 1001,
  autoAccessFixed: 1
}
2022-10-22 20:31:11.214 - [Info] MITM Version: 2
2022-10-22 20:31:11.216 - [Info] Auto Access Enabled: true
2022-10-22 20:31:11.216 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-22 20:31:11.222 - [Info] SSH man-in-the-middle server for 10.0.3.244 listening on 10.0.3.1:1001
2022-10-22 20:39:22.437 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.439 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.440 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.441 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.441 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.447 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.447 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.448 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.448 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.449 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.452 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.453 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.454 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.455 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.455 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.458 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.458 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:22.458 - [Debug] [Connection] Attacker connected: 34.133.67.239 | Client Identification: SSH-2.0-Go
2022-10-22 20:39:52.550 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.550 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.571 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.571 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.572 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.572 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.573 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.573 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.573 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.574 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.578 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.578 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.579 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.579 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.581 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.581 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.583 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.583 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.583 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.583 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.590 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.590 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.593 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.593 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:39:52.613 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:39:52.613 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:40:01.328 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.329 - [Debug] [Auto Access] Attacker: 34.133.67.239, Threshold: 1, Attempts: 1
2022-10-22 20:40:01.329 - [Debug] [Auto Access] Compromising the honeypot
2022-10-22 20:40:01.329 - [Debug] [Auto Access] Adding the following credentials: 'root:1234'
2022-10-22 20:40:01.388 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-22 20:40:01.390 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-22 20:40:01.390 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.244
2022-10-22 20:40:01.404 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.405 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-22 20:40:01.406 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.407 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.407 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 20:40:01.408 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.410 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.411 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 20:40:01.411 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.412 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.413 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 20:40:01.413 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.414 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.414 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-22 20:40:01.414 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.415 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.415 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 20:40:01.415 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.416 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.416 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 20:40:01.417 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.417 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.417 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 20:40:01.417 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.426 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.427 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 20:40:01.427 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.427 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.427 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-22 20:40:01.428 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.428 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.428 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 20:40:01.428 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.429 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'password'
2022-10-22 20:40:01.429 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2022-10-22 20:40:01.429 - [Debug] [Auth] Attacker: 34.133.67.239 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 20:40:01.456 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2022-10-22 20:40:06.595 - [Debug] [Auth] Attacker 34.133.67.239 trying to authenticate with 'none'
2022-10-22 20:40:06.595 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 20:40:12.234 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.236 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.236 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.237 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.244 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.246 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.255 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.256 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.256 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.257 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.264 - [Debug] [Connection] Attacker closed the connection
2022-10-22 20:40:12.281 - [Debug] [Connection] Attacker closed the connection
