
(node:2136035) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_2',
  containerIp: '10.0.3.96',
  mitmPort: 1001,
  autoAccessFixed: 1
}
Error: ENOENT: no such file or directory, open '/var/lib/lxc/DATABASE_2/rootfs/etc/ssh/ssh_host_ecdsa_key'
    at Object.openSync (node:fs:594:3)
    at Object.readFileSync (node:fs:462:35)
    at readKeys (/home/student/MITM/server/keys.js:19:18)
    at readCTKeys (/home/student/MITM/server/keys.js:29:15)
    at Object.loadKeys (/home/student/MITM/server/keys.js:48:12)
    at Object.<anonymous> (/home/student/MITM/server/index.js:158:29)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/lib/lxc/DATABASE_2/rootfs/etc/ssh/ssh_host_ecdsa_key'
}
[ERROR] Could not read the keys from the container! Is the container mounted/running and is openssh-server installed?
{"level":"error","message":"Forever detected script exited with code: 1"}
(node:2147584) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_2',
  containerIp: '10.0.3.33',
  mitmPort: 1001,
  autoAccessFixed: 1
}
2022-10-23 09:52:24.578 - [Info] MITM Version: 2
2022-10-23 09:52:24.580 - [Info] Auto Access Enabled: true
2022-10-23 09:52:24.580 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-23 09:52:24.596 - [Info] SSH man-in-the-middle server for 10.0.3.33 listening on 10.0.3.1:1001
2022-10-23 09:52:24.955 - [Debug] [Connection] Attacker connected: 223.171.91.148 | Client Identification: SSH-2.0-Go
2022-10-23 09:52:25.226 - [Debug] [Connection] Attacker connected: 118.218.209.149 | Client Identification: SSH-2.0-Go
2022-10-23 09:52:25.498 - [Debug] [Connection] Attacker connected: 209.216.177.158 | Client Identification: SSH-2.0-Go
2022-10-23 09:52:26.057 - [Debug] [Auth] Attacker 209.216.177.158 trying to authenticate with 'none'
2022-10-23 09:52:26.057 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 09:52:26.265 - [Debug] [Auth] Attacker 209.216.177.158 trying to authenticate with 'publickey'
2022-10-23 09:52:26.267 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 09:52:26.267 - [Debug] [Auth] Attacker: 209.216.177.158 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 09:52:26.472 - [Debug] [Auth] Attacker 118.218.209.149 trying to authenticate with 'none'
2022-10-23 09:52:26.472 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 09:52:26.478 - [Debug] [Connection] Attacker closed the connection
2022-10-23 09:52:26.546 - [Debug] [Auth] Attacker 223.171.91.148 trying to authenticate with 'none'
2022-10-23 09:52:26.546 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 09:52:26.565 - [Debug] [Connection] Attacker connected: 209.216.177.158 | Client Identification: SSH-2.0-Go
2022-10-23 09:52:26.670 - [Debug] [Connection] Attacker connected: 184.67.149.186 | Client Identification: SSH-2.0-Go
2022-10-23 09:52:26.911 - [Debug] [Auth] Attacker 118.218.209.149 trying to authenticate with 'password'
2022-10-23 09:52:26.911 - [Debug] [Auto Access] Attacker: 118.218.209.149, Threshold: 1, Attempts: 1
2022-10-23 09:52:26.911 - [Debug] [Auto Access] Compromising the honeypot
2022-10-23 09:52:26.911 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-23 09:52:27.114 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-23 09:52:27.116 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-23 09:52:27.117 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.33
2022-10-23 09:52:27.134 - [Debug] [Auth] Attacker 223.171.91.148 trying to authenticate with 'password'
2022-10-23 09:52:27.139 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-23 09:52:27.139 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.33
