
2022-10-23 11:14:21.826 - [Debug] [Auth] Attacker 144.22.130.100 trying to authenticate with 'publickey'
2022-10-23 11:14:21.827 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 11:14:21.828 - [Debug] [Auth] Attacker: 144.22.130.100 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 11:14:21.966 - [Debug] [Connection] Attacker connected: 89.121.228.38 | Client Identification: SSH-2.0-Go
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:2606025) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.123',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-23 11:14:49.149 - [Info] MITM Version: 2
2022-10-23 11:14:49.151 - [Info] Auto Access Enabled: true
2022-10-23 11:14:49.151 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-23 11:14:49.158 - [Info] SSH man-in-the-middle server for 10.0.3.123 listening on 10.0.3.1:1000
2022-10-23 11:14:50.193 - [Debug] [Connection] Attacker connected: 139.59.135.142 | Client Identification: SSH-2.0-Go
2022-10-23 11:14:50.819 - [Debug] [Auth] Attacker 139.59.135.142 trying to authenticate with 'none'
2022-10-23 11:14:50.820 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 11:14:51.014 - [Debug] [Auth] Attacker 139.59.135.142 trying to authenticate with 'publickey'
2022-10-23 11:14:51.015 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 11:14:51.016 - [Debug] [Auth] Attacker: 139.59.135.142 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 11:14:51.210 - [Debug] [Connection] Attacker closed the connection
2022-10-23 11:14:51.307 - [Debug] [Connection] Attacker connected: 139.59.135.142 | Client Identification: SSH-2.0-Go
