
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:3359439) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_4',
  containerIp: '10.0.3.92',
  mitmPort: 1003,
  autoAccessFixed: 1
}
2022-10-23 03:35:38.971 - [Info] MITM Version: 2
2022-10-23 03:35:38.972 - [Info] Auto Access Enabled: true
2022-10-23 03:35:38.972 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-23 03:35:38.979 - [Info] SSH man-in-the-middle server for 10.0.3.92 listening on 10.0.3.1:1003
2022-10-23 03:39:32.677 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:32.679 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:32.681 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:32.683 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:32.684 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:32.685 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:32.685 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:32.686 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:33.598 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:33.598 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:33.601 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:37.562 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:37.566 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:37.567 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:37.571 - [Debug] [Connection] Attacker connected: 34.159.168.111 | Client Identification: SSH-2.0-Go
2022-10-23 03:39:51.624 - [Debug] [Auth] Attacker 34.159.168.111 trying to authenticate with 'none'
2022-10-23 03:39:51.625 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 03:39:54.792 - [Debug] [Auth] Attacker 34.159.168.111 trying to authenticate with 'none'
2022-10-23 03:39:54.792 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 03:40:03.069 - [Debug] [Auth] Attacker 34.159.168.111 trying to authenticate with 'password'
2022-10-23 03:40:03.069 - [Debug] [Auto Access] Attacker: 34.159.168.111, Threshold: 1, Attempts: 1
2022-10-23 03:40:03.069 - [Debug] [Auto Access] Compromising the honeypot
2022-10-23 03:40:03.070 - [Debug] [Auto Access] Adding the following credentials: 'ubnt:ubnt'
2022-10-23 03:40:03.188 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-23 03:40:03.190 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-23 03:40:03.190 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.92
2022-10-23 03:40:03.243 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2022-10-23 03:40:06.633 - [Debug] [Auth] Attacker 34.159.168.111 trying to authenticate with 'password'
2022-10-23 03:40:06.635 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Container user is disabled
2022-10-23 03:40:06.635 - [Debug] [Auth] Attacker: 34.159.168.111 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 03:40:10.025 - [Debug] [Auth] Attacker 34.159.168.111 trying to authenticate with 'none'
2022-10-23 03:40:10.025 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 03:40:15.544 - [Debug] [Connection] Attacker closed the connection
2022-10-23 03:40:15.581 - [Debug] [Auth] Attacker 34.159.168.111 trying to authenticate with 'none'
2022-10-23 03:40:15.581 - [Debug] [Auth] Attacker authentication error: No authentication method provided
