
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:2241270) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_3',
  containerIp: '10.0.3.43',
  mitmPort: 1002,
  autoAccessFixed: 1
}
2022-10-22 19:31:17.277 - [Info] MITM Version: 2
2022-10-22 19:31:17.278 - [Info] Auto Access Enabled: true
2022-10-22 19:31:17.278 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-22 19:31:17.285 - [Info] SSH man-in-the-middle server for 10.0.3.43 listening on 10.0.3.1:1002
2022-10-22 19:34:26.172 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:26.174 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:26.174 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:26.175 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:26.186 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:26.186 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:26.186 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:26.189 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:26.190 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:27.020 - [Debug] [Connection] Attacker connected: 35.234.111.18 | Client Identification: SSH-2.0-Go
2022-10-22 19:34:38.973 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:38.974 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:38.975 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:38.975 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:39.002 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:39.003 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:39.009 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:39.009 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:39.009 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:39.009 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:39.010 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:39.010 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:39.016 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:39.016 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:39.017 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:39.017 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:39.018 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:39.018 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:39.466 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'none'
2022-10-22 19:34:39.467 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-22 19:34:42.099 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.100 - [Debug] [Auto Access] Attacker: 35.234.111.18, Threshold: 1, Attempts: 1
2022-10-22 19:34:42.100 - [Debug] [Auto Access] Compromising the honeypot
2022-10-22 19:34:42.100 - [Debug] [Auto Access] Adding the following credentials: 'root:changeme'
2022-10-22 19:34:42.150 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-22 19:34:42.152 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-22 19:34:42.152 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.43
2022-10-22 19:34:42.166 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.166 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:42.167 - [Debug] [Auth] Attacker: 35.234.111.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:42.170 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.171 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:42.174 - [Debug] [Auth] Attacker: 35.234.111.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:42.174 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.174 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:42.175 - [Debug] [Auth] Attacker: 35.234.111.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:42.175 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.175 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:42.175 - [Debug] [Auth] Attacker: 35.234.111.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:42.176 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.176 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:42.176 - [Debug] [Auth] Attacker: 35.234.111.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:42.176 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.178 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:42.178 - [Debug] [Auth] Attacker: 35.234.111.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:42.179 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.179 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:42.179 - [Debug] [Auth] Attacker: 35.234.111.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:42.179 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.180 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:42.180 - [Debug] [Auth] Attacker: 35.234.111.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:42.205 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2022-10-22 19:34:42.467 - [Debug] [Auth] Attacker 35.234.111.18 trying to authenticate with 'password'
2022-10-22 19:34:42.467 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:42.468 - [Debug] [Auth] Attacker: 35.234.111.18 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:43.992 - [Debug] [Connection] Attacker connected: 141.98.11.91 | Client Identification: SSH-2.0-libssh2_1.4.3
2022-10-22 19:34:45.067 - [Debug] [Auth] Attacker 141.98.11.91 trying to authenticate with 'password'
2022-10-22 19:34:45.067 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2022-10-22 19:34:45.068 - [Debug] [Auth] Attacker: 141.98.11.91 has so far made 1 attempts. Remaining: 5 attempts
2022-10-22 19:34:45.342 - [Debug] [Connection] Attacker closed the connection
