
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:578656) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_3',
  containerIp: '10.0.3.100',
  mitmPort: 1002,
  autoAccessFixed: 1
}
2022-10-23 20:52:41.030 - [Info] MITM Version: 2
2022-10-23 20:52:41.031 - [Info] Auto Access Enabled: true
2022-10-23 20:52:41.032 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-23 20:52:41.038 - [Info] SSH man-in-the-middle server for 10.0.3.100 listening on 10.0.3.1:1002
2022-10-23 20:52:41.707 - [Debug] [Connection] Attacker connected: 58.216.8.121 | Client Identification: SSH-2.0-Go
2022-10-23 20:52:42.742 - [Debug] [Connection] Attacker connected: 82.64.113.245 | Client Identification: SSH-2.0-Go
2022-10-23 20:52:43.097 - [Debug] [Auth] Attacker 58.216.8.121 trying to authenticate with 'none'
2022-10-23 20:52:43.097 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 20:52:43.313 - [Debug] [Auth] Attacker 82.64.113.245 trying to authenticate with 'none'
2022-10-23 20:52:43.313 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 20:52:43.501 - [Debug] [Connection] Attacker connected: 223.171.91.136 | Client Identification: SSH-2.0-Go
2022-10-23 20:52:43.528 - [Debug] [Auth] Attacker 82.64.113.245 trying to authenticate with 'publickey'
2022-10-23 20:52:43.530 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 20:52:43.530 - [Debug] [Auth] Attacker: 82.64.113.245 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 20:52:43.587 - [Debug] [Auth] Attacker 58.216.8.121 trying to authenticate with 'publickey'
2022-10-23 20:52:43.588 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 20:52:43.588 - [Debug] [Auth] Attacker: 58.216.8.121 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 20:52:43.744 - [Debug] [Connection] Attacker closed the connection
2022-10-23 20:52:43.829 - [Debug] [Connection] Attacker connected: 82.64.113.245 | Client Identification: SSH-2.0-Go
2022-10-23 20:52:44.076 - [Debug] [Connection] Attacker closed the connection
