
2022-10-23 16:19:54.980 - [Debug] [Connection] Attacker connected: 58.216.8.121 | Client Identification: SSH-2.0-Go
2022-10-23 16:19:55.183 - [Debug] [Auth] Attacker 129.154.55.234 trying to authenticate with 'none'
2022-10-23 16:19:55.183 - [Debug] [Auth] Attacker authentication error: No authentication method provided
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:3797048) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_3',
  containerIp: '10.0.3.160',
  mitmPort: 1002,
  autoAccessFixed: 1
}
2022-10-23 16:20:28.423 - [Info] MITM Version: 2
2022-10-23 16:20:28.425 - [Info] Auto Access Enabled: true
2022-10-23 16:20:28.426 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-23 16:20:28.446 - [Info] SSH man-in-the-middle server for 10.0.3.160 listening on 10.0.3.1:1002
2022-10-23 16:20:30.033 - [Debug] [Connection] Attacker connected: 185.55.64.228 | Client Identification: SSH-2.0-Go
2022-10-23 16:20:30.606 - [Debug] [Connection] Attacker connected: 120.236.79.182 | Client Identification: SSH-2.0-Go
2022-10-23 16:20:30.808 - [Debug] [Auth] Attacker 185.55.64.228 trying to authenticate with 'none'
2022-10-23 16:20:30.809 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 16:20:31.048 - [Debug] [Auth] Attacker 185.55.64.228 trying to authenticate with 'publickey'
2022-10-23 16:20:31.049 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 16:20:31.050 - [Debug] [Auth] Attacker: 185.55.64.228 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 16:20:31.286 - [Debug] [Connection] Attacker closed the connection
2022-10-23 16:20:31.412 - [Debug] [Connection] Attacker connected: 185.55.64.228 | Client Identification: SSH-2.0-Go
