
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:3714291) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_3',
  containerIp: '10.0.3.191',
  mitmPort: 1002,
  autoAccessFixed: 1
}
2022-10-23 16:00:27.369 - [Info] MITM Version: 2
2022-10-23 16:00:27.371 - [Info] Auto Access Enabled: true
2022-10-23 16:00:27.371 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-23 16:00:27.378 - [Info] SSH man-in-the-middle server for 10.0.3.191 listening on 10.0.3.1:1002
2022-10-23 16:00:27.780 - [Debug] [Connection] Attacker connected: 121.200.53.148 | Client Identification: SSH-2.0-Go
2022-10-23 16:00:28.923 - [Debug] [Connection] Attacker connected: 31.165.5.155 | Client Identification: SSH-2.0-Go
2022-10-23 16:00:29.179 - [Debug] [Connection] Attacker connected: 69.236.215.6 | Client Identification: SSH-2.0-Go
2022-10-23 16:00:29.234 - [Debug] [Auth] Attacker 121.200.53.148 trying to authenticate with 'none'
2022-10-23 16:00:29.234 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 16:00:29.442 - [Debug] [Auth] Attacker 69.236.215.6 trying to authenticate with 'none'
2022-10-23 16:00:29.442 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 16:00:29.543 - [Debug] [Auth] Attacker 69.236.215.6 trying to authenticate with 'publickey'
2022-10-23 16:00:29.544 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 16:00:29.546 - [Debug] [Auth] Attacker: 69.236.215.6 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 16:00:29.642 - [Debug] [Connection] Attacker closed the connection
2022-10-23 16:00:29.675 - [Debug] [Connection] Attacker connected: 69.236.215.6 | Client Identification: SSH-2.0-Go
2022-10-23 16:00:29.745 - [Debug] [Auth] Attacker 121.200.53.148 trying to authenticate with 'publickey'
2022-10-23 16:00:29.746 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 16:00:29.746 - [Debug] [Auth] Attacker: 121.200.53.148 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 16:00:29.763 - [Debug] [Auth] Attacker 31.165.5.155 trying to authenticate with 'none'
2022-10-23 16:00:29.763 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 16:00:29.933 - [Debug] [Auth] Attacker 69.236.215.6 trying to authenticate with 'none'
2022-10-23 16:00:29.934 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 16:00:30.031 - [Debug] [Connection] Attacker connected: 84.16.224.173 | Client Identification: SSH-2.0-Go
2022-10-23 16:00:30.032 - [Debug] [Auth] Attacker 69.236.215.6 trying to authenticate with 'password'
2022-10-23 16:00:30.032 - [Debug] [Auto Access] Attacker: 69.236.215.6, Threshold: 1, Attempts: 1
2022-10-23 16:00:30.032 - [Debug] [Auto Access] Compromising the honeypot
2022-10-23 16:00:30.032 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-23 16:00:30.170 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-23 16:00:30.172 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-23 16:00:30.172 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.191
2022-10-23 16:00:30.185 - [Debug] [Auth] Attacker 31.165.5.155 trying to authenticate with 'publickey'
2022-10-23 16:00:30.186 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 16:00:30.189 - [Debug] [Auth] Attacker: 31.165.5.155 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 16:00:30.237 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2022-10-23 16:00:30.255 - [Debug] [Connection] Attacker closed the connection
