
2022-10-23 18:37:00.963 - [Debug] [Auth] Attacker 118.41.204.72 trying to authenticate with 'none'
2022-10-23 18:37:00.963 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 18:37:01.039 - [Debug] [Connection] Attacker connected: 59.1.226.211 | Client Identification: SSH-2.0-Go
2022-10-23 18:37:01.067 - [Debug] [Connection] Attacker connected: 1.220.98.197 | Client Identification: SSH-2.0-Go
2022-10-23 18:37:01.407 - [Debug] [Auth] Attacker 175.178.247.209 trying to authenticate with 'none'
2022-10-23 18:37:01.407 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 18:37:01.482 - [Debug] [Auth] Attacker 118.41.204.72 trying to authenticate with 'password'
2022-10-23 18:37:01.482 - [Debug] [Auto Access] Attacker: 118.41.204.72, Threshold: 1, Attempts: 1
2022-10-23 18:37:01.482 - [Debug] [Auto Access] Compromising the honeypot
2022-10-23 18:37:01.482 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-23 18:37:03.072 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-23 18:37:03.074 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-23 18:37:03.074 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.123
2022-10-23 18:37:03.088 - [Debug] [Auth] Attacker 222.117.95.174 trying to authenticate with 'none'
2022-10-23 18:37:03.088 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 18:37:03.090 - [Debug] [Auth] Attacker 175.178.247.209 trying to authenticate with 'publickey'
2022-10-23 18:37:03.097 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 18:37:03.099 - [Debug] [Auth] Attacker: 175.178.247.209 has so far made 1 attempts. Remaining: 5 attempts
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:158667) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.30',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-23 18:37:35.497 - [Info] MITM Version: 2
2022-10-23 18:37:35.498 - [Info] Auto Access Enabled: true
2022-10-23 18:37:35.498 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-23 18:37:35.506 - [Info] SSH man-in-the-middle server for 10.0.3.30 listening on 10.0.3.1:1000
2022-10-23 18:37:37.160 - [Debug] [Connection] Attacker connected: 62.12.108.44 | Client Identification: SSH-2.0-Go
2022-10-23 18:37:37.600 - [Debug] [Connection] Attacker connected: 5.28.139.161 | Client Identification: SSH-2.0-Go
2022-10-23 18:37:38.153 - [Debug] [Auth] Attacker 62.12.108.44 trying to authenticate with 'none'
2022-10-23 18:37:38.154 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 18:37:38.357 - [Debug] [Connection] Attacker connected: 69.236.215.6 | Client Identification: SSH-2.0-Go
2022-10-23 18:37:38.514 - [Debug] [Auth] Attacker 62.12.108.44 trying to authenticate with 'publickey'
2022-10-23 18:37:38.516 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 18:37:38.517 - [Debug] [Auth] Attacker: 62.12.108.44 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 18:37:38.623 - [Debug] [Auth] Attacker 69.236.215.6 trying to authenticate with 'none'
2022-10-23 18:37:38.624 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 18:37:38.724 - [Debug] [Auth] Attacker 69.236.215.6 trying to authenticate with 'publickey'
2022-10-23 18:37:38.725 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-23 18:37:38.726 - [Debug] [Auth] Attacker: 69.236.215.6 has so far made 1 attempts. Remaining: 5 attempts
2022-10-23 18:37:38.824 - [Debug] [Connection] Attacker closed the connection
2022-10-23 18:37:38.863 - [Debug] [Connection] Attacker connected: 69.236.215.6 | Client Identification: SSH-2.0-Go
2022-10-23 18:37:38.873 - [Debug] [Connection] Attacker closed the connection
2022-10-23 18:37:39.033 - [Debug] [Connection] Attacker connected: 62.12.108.44 | Client Identification: SSH-2.0-Go
2022-10-23 18:37:39.113 - [Debug] [Auth] Attacker 69.236.215.6 trying to authenticate with 'none'
2022-10-23 18:37:39.114 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-23 18:37:39.235 - [Debug] [Auth] Attacker 69.236.215.6 trying to authenticate with 'password'
2022-10-23 18:37:39.281 - [Debug] [Auto Access] Attacker: 69.236.215.6, Threshold: 1, Attempts: 1
2022-10-23 18:37:39.281 - [Debug] [Auto Access] Compromising the honeypot
2022-10-23 18:37:39.281 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
